### ISSUE TITLE
Memory Footprint

### ISSUE THREAD

**Issue by Upasna55** [csl-iisc/dpPred-cbPred#2]
As per the `Dead Page and Dead Block Predictors, HPCA 2021` Paper, the memory footprint of various GAPBS Graph Kernels is mentioned. But, the **datasets** on which these graph kernels have been executed is not mentioned. In view of this, I would like to get clarifications on the following:  
1. Which graph datasets have you used? 
2. Is the Memory Footprint mentioned there, is average for graph kernels executed on various datasets? 
3. Further, I would like to know how you've calculated the memory footprint, given that Sniper doesn't provide DRAM Page Level Information?

**Comment by prachatos** [comment]
I responded via email, but for anyone looking for the details - we used 2^20 and 2^21 graphs for GAPBS, with 2^21 only for SSSP. The memory footprint was measured by running the kernels on the actual system without Sniper and represented an approximate average size.

I'll add this to the documentation of the repo as well.

**Comment by Upasna55** [comment]
Prachatos, have you calculated per-process memory usage using PID(Process ID)? Further, most linux commands give run-time memory usage, i.e. memory usage of a program at certain point of time and not the memory footprint from the beginning of a program execution till its completion. Are the stats mentioned in the paper, for complete program execution or memory usage at certain point of time during execution?

**Comment by prachatos** [comment]
I don't recall off the top of my head what command we used to measure the footprints, but something like `/usr/bin/time -v <cmd>` shows the MaxRSS. The stats in the paper reflect the peak size.

**Comment by Upasna55** [comment]
Ok Prachatos. Thanks for your reply.
